// Data extracted from KM2 PDFs
// Format: translations have ru (Russian) and en (English with / for alternatives)
//         abbreviations have abbr and full
//         definitions have term and def

const TRANSLATIONS = [
  {ru: "точка доступа", en: "access point"},
  {ru: "время доступа", en: "access time / seek time"},
  {ru: "сложение", en: "addition"},
  {ru: "рекламное ПО", en: "adware"},
  {ru: "искусственный интеллект", en: "AI / artificial intelligence"},
  {ru: "аналоговый и цифровой сигналы", en: "analog and digital signals"},
  {ru: "код приложения", en: "application code"},
  {ru: "приложение", en: "application / app"},
  {ru: "дополненная реальность", en: "AR / augmented reality"},
  {ru: "арифметико-логическое устройство", en: "ALU / arithmetic logic unit"},
  {ru: "искусственная нейронная сеть", en: "artificial neural network / ANN"},
  {ru: "ассемблер", en: "assembler"},
  {ru: "языки ассемблера", en: "assembly languages"},
  {ru: "асинхронная передача данных", en: "asynchronous transmission"},
  {ru: "затухание сигнала / ослабление сигнала", en: "attenuation of a signal"},
  {ru: "магистраль", en: "backbone"},
  {ru: "лазейка в системе безопасности", en: "backdoor"},
  {ru: "разработка серверных компонентов приложения", en: "backend development"},
  {ru: "фоновые шаблоны", en: "background templates"},
  {ru: "алгоритм обратного распространения ошибки", en: "backpropagation"},
  {ru: "резервное копирование", en: "backup"},
  {ru: "пропускная способность", en: "bandwidth"},
  {ru: "базовая система ввода/вывода", en: "BIOS / basic input output system"},
  {ru: "аккумуляторная батарея", en: "battery pack"},
  {ru: "двоичный код", en: "binary code"},
  {ru: "биометрические средства защиты", en: "biometric security devices"},
  {ru: "мост (сетевое устройство)", en: "bridge"},
  {ru: "широкополосный интернет", en: "broadband connection"},
  {ru: "встроенная камера", en: "built-in webcam"},
  {ru: "шина", en: "bus"},
  {ru: "разрядность шины", en: "bus width"},
  {ru: "топология общая шина", en: "bus topology"},
  {ru: "когерентность кэша", en: "cache coherency"},
  {ru: "попадание в кэш", en: "cache hit"},
  {ru: "промах кэша", en: "cache miss"},
  {ru: "размер кэш-строки", en: "cache line size"},
  {ru: "вычисления", en: "calculations"},
  {ru: "конденсатор", en: "capacitor"},
  {ru: "сотовая связь", en: "cellular connection"},
  {ru: "центральный процессор", en: "CPU / central processing unit"},
  {ru: "печатная плата", en: "circuit board"},
  {ru: "архитектура клиент-сервер", en: "client-server architecture"},
  {ru: "тактовая частота", en: "clock speed"},
  {ru: "облачные вычисления", en: "cloud computing"},
  {ru: "коаксиальный кабель", en: "coaxial cable"},
  {ru: "совместимый", en: "compatible"},
  {ru: "компилятор", en: "compiler"},
  {ru: "согласованные данные", en: "consistent data"},
  {ru: "блок управления", en: "control unit"},
  {ru: "кооперативная многозадачность / невытесняющая многозадачность", en: "cooperative multitasking"},
  {ru: "медный провод", en: "copper cable"},
  {ru: "автоматизированная поисковая система", en: "crawler-based search engine"},
  {ru: "сканирование информации", en: "crawling"},
  {ru: "каскадные таблицы стилей", en: "CSS / cascading style sheets"},
  {ru: "канальный уровень", en: "data link layer"},
  {ru: "передача данных", en: "data transmission"},
  {ru: "коммутация дейтаграммных пакетов", en: "datagram packet switching"},
  {ru: "распределённая атака на отказ в обслуживании", en: "DDoS attack / distributed denial of service"},
  {ru: "отладка", en: "debugging"},
  {ru: "выделенная линия", en: "dedicated line"},
  {ru: "настройки по умолчанию", en: "default settings"},
  {ru: "задержка передачи сигнала", en: "delay / latency"},
  {ru: "стационарный компьютер", en: "desktop PC"},
  {ru: "съёмная клавиатура", en: "detachable keyboard"},
  {ru: "коммутируемое соединение", en: "dial-up connection"},
  {ru: "разностное резервное копирование / частичное копирование", en: "differential backup"},
  {ru: "цифровой сигнал", en: "digital signal"},
  {ru: "цифровая абонентская линия", en: "DSL / digital subscriber line"},
  {ru: "каталог / папка", en: "directory"},
  {ru: "искажение сигнала", en: "distortion of a signal"},
  {ru: "деление", en: "division"},
  {ru: "скорость скачивания / скорость загрузки", en: "download speed"},
  {ru: "инкапсуляция", en: "encapsulation"},
  {ru: "шифрование", en: "encryption"},
  {ru: "энергопотребление", en: "energy consumption"},
  {ru: "перезаписываемый", en: "erasable"},
  {ru: "исполняемый файл", en: "executable file"},
  {ru: "карта расширения", en: "expansion card"},
  {ru: "слоты расширения", en: "expansion slots"},
  {ru: "внешний жёсткий диск", en: "external hard disk drive / external HDD"},
  {ru: "характеристика / особенность", en: "feature"},
  {ru: "оптоволоконный кабель", en: "fiber-optic cables"},
  {ru: "брандмауэр / межсетевой экран", en: "firewall"},
  {ru: "прошивка", en: "firmware"},
  {ru: "флэшка", en: "flash drive"},
  {ru: "транзистор с плавающим затвором", en: "floating gate transistor"},
  {ru: "дискета", en: "floppy disk"},
  {ru: "шрифт", en: "font"},
  {ru: "нижний колонтитул", en: "footer"},
  {ru: "форматирование", en: "formatting"},
  {ru: "бесплатное ПО", en: "freeware"},
  {ru: "системная шина / фронтальная шина", en: "front side bus"},
  {ru: "протокол передачи данных (FTP)", en: "FTP / file transfer protocol"},
  {ru: "полносвязные нейросети", en: "fully connected neural networks"},
  {ru: "шлюз / межсетевой шлюз", en: "gateway"},
  {ru: "геостационарный спутник", en: "geostationary satellite"},
  {ru: "графический интерфейс пользователя", en: "GUI / graphical user interface"},
  {ru: "портативные устройства", en: "handheld / palmtop / portable devices"},
  {ru: "аппаратное обеспечение", en: "hardware"},
  {ru: "верхний колонтитул", en: "header"},
  {ru: "авария головки (поломка магнитной головки HDD)", en: "head crash"},
  {ru: "наушники", en: "headphones"},
  {ru: "сотрудник службы технической поддержки", en: "help-desk troubleshooter / technician"},
  {ru: "эвристическое сканирование", en: "heuristic scanning"},
  {ru: "скрытые элементы / скрытые слои", en: "hidden units"},
  {ru: "высокоуровневый язык", en: "high level language"},
  {ru: "высокоскоростное интернет-соединение", en: "high-speed internet connection"},
  {ru: "межсетевой экран узлов (программный)", en: "host-based firewall"},
  {ru: "общая точка доступа", en: "hot spot"},
  {ru: "язык разметки гипертекста", en: "HTML / hypertext markup language"},
  {ru: "протокол гипертекстовой передачи", en: "HTTP / hypertext transfer protocol"},
  {ru: "концентратор / повторитель", en: "hub"},
  {ru: "веб-каталог", en: "human-powered directory"},
  {ru: "гиперссылки", en: "hyperlinks"},
  {ru: "выборочное копирование", en: "incremental backup"},
  {ru: "индексирование", en: "indexing"},
  {ru: "отступ", en: "indent"},
  {ru: "устройство ввода/вывода", en: "input output device"},
  {ru: "регистр инструкций", en: "IR / instruction register"},
  {ru: "интегральная схема / микросхема", en: "integrated circuits"},
  {ru: "взаимосвязанные узлы", en: "interconnected nodes"},
  {ru: "внутреннее/внешнее устройство хранения", en: "internal external storage device"},
  {ru: "доступ к интернету", en: "internet access"},
  {ru: "интерпретатор", en: "interpreter"},
  {ru: "наследование", en: "inheritance"},
  {ru: "интернет вещей", en: "IoT / internet of things"},
  {ru: "команда перехода", en: "jump command"},
  {ru: "ядро (ОС)", en: "kernel"},
  {ru: "основные характеристики / отличительные признаки", en: "key features"},
  {ru: "клавиатурный шпион", en: "keylogger"},
  {ru: "ноутбук", en: "laptop"},
  {ru: "лазерный луч", en: "laser beam"},
  {ru: "расположение / макет сайта", en: "layout"},
  {ru: "межстрочный интервал", en: "line spacing"},
  {ru: "локальная сеть", en: "LAN / local area network"},
  {ru: "жидкокристаллический дисплей", en: "LCD / liquid crystal display"},
  {ru: "нижний регистр", en: "lowercase"},
  {ru: "низкоуровневый язык", en: "low-level language"},
  {ru: "машинное обучение", en: "machine learning / ML"},
  {ru: "магнитная лента", en: "magnetic tape"},
  {ru: "мейнфрейм / мощный сервер", en: "mainframe"},
  {ru: "сделать резервную копию", en: "make a backup"},
  {ru: "вредоносное ПО", en: "malware"},
  {ru: "городская сеть", en: "MAN / metropolitan area network"},
  {ru: "поля (документа)", en: "margins"},
  {ru: "теги разметки", en: "markup tags"},
  {ru: "выделение памяти / распределение памяти", en: "memory allocation"},
  {ru: "объём памяти", en: "memory capacity"},
  {ru: "карта памяти", en: "memory card"},
  {ru: "ячеистая топология / топология сетки", en: "mesh topology"},
  {ru: "метапоисковая система", en: "meta-search engine"},
  {ru: "процедура дезориентации", en: "misdirection routine"},
  {ru: "многоядерный процессор", en: "multi-core CPU"},
  {ru: "умножение", en: "multiplication"},
  {ru: "многозадачный", en: "multi-tasking"},
  {ru: "вложенные папки", en: "nested folders"},
  {ru: "безопасность в сети", en: "network security"},
  {ru: "топология сети", en: "network topology"},
  {ru: "сетевой брандмауэр", en: "network-based firewall"},
  {ru: "нейронная сеть", en: "neural network"},
  {ru: "узел сети", en: "node"},
  {ru: "энергонезависимый", en: "non-volatile"},
  {ru: "внешняя поисковая оптимизация", en: "off-page SEO"},
  {ru: "пакет офисных приложений", en: "office suite / office package"},
  {ru: "поисковая оптимизация страницы", en: "on-page SEO"},
  {ru: "программы с открытым исходным кодом", en: "open-source software"},
  {ru: "естественные результаты поиска", en: "organic results"},
  {ru: "модель взаимодействия открытых систем", en: "OSI model / open systems interconnection"},
  {ru: "блок вывода", en: "output unit"},
  {ru: "вирус перезаписи", en: "overwriting virus"},
  {ru: "пакетная коммутация", en: "packet switching"},
  {ru: "исходный код страницы", en: "page source code"},
  {ru: "частица", en: "particle"},
  {ru: "раздел на жёстком диске", en: "partition"},
  {ru: "полезная нагрузка (вируса)", en: "payload"},
  {ru: "счётчик команд / программный счётчик", en: "PC / program counter"},
  {ru: "одноранговая сеть", en: "peer-to-peer architecture"},
  {ru: "производительность", en: "performance"},
  {ru: "подключаемое оборудование / периферия", en: "peripherals"},
  {ru: "персональная сеть", en: "PAN / personal area network"},
  {ru: "повсеместные вычисления", en: "pervasive computing"},
  {ru: "фишинг / выуживание паролей", en: "phishing"},
  {ru: "несанкционированное проникновение вслед за пользователем", en: "piggybacking"},
  {ru: "ячейка памяти оптического диска", en: "pit"},
  {ru: "открытый текст / незашифрованный текст", en: "plaintext"},
  {ru: "пластина жёсткого диска", en: "platter"},
  {ru: "блок питания", en: "power-supply unit"},
  {ru: "вытесняющая многозадачность", en: "preemptive multitasking"},
  {ru: "основное запоминающее устройство", en: "primary storage"},
  {ru: "закрытое программное обеспечение / проприетарное ПО", en: "proprietary software"},
  {ru: "протокол (набор правил)", en: "protocol"},
  {ru: "перфокарта", en: "punched card"},
  {ru: "оперативное запоминающее устройство (ОЗУ)", en: "RAM / random access memory"},
  {ru: "ранжирование", en: "ranking"},
  {ru: "программы-вымогатели", en: "ransomware"},
  {ru: "необработанные данные", en: "raw data"},
  {ru: "постоянное запоминающее устройство (ПЗУ)", en: "ROM / read only memory"},
  {ru: "головка чтения/записи", en: "read-write head"},
  {ru: "операционная система реального времени", en: "real-time OS"},
  {ru: "регистры процессора", en: "registers"},
  {ru: "удалённый доступ", en: "remote access"},
  {ru: "процедура самокопирования / процедура воспроизводства", en: "reproduction routine"},
  {ru: "запрос (к поиску)", en: "request / query / search string"},
  {ru: "кольцевая топология", en: "ring topology"},
  {ru: "робототехника", en: "robotics"},
  {ru: "маршрутизатор", en: "router"},
  {ru: "спутниковая связь", en: "satellite connection"},
  {ru: "доступ к спутниковому интернету", en: "satellite internet access"},
  {ru: "поисковая система", en: "search engine"},
  {ru: "база данных поисковика", en: "search index"},
  {ru: "строка поиска", en: "search box / search bar"},
  {ru: "меры безопасности", en: "security measures"},
  {ru: "полупроводник", en: "semiconductor"},
  {ru: "полупроводниковая технология", en: "semiconductor technology"},
  {ru: "конфиденциальные данные", en: "sensitive data"},
  {ru: "поисковая оптимизация (SEO)", en: "SEO / search engine optimization"},
  {ru: "сеансовый уровень", en: "session layer"},
  {ru: "заливка", en: "shading"},
  {ru: "условно бесплатное ПО", en: "shareware"},
  {ru: "сигнатурное сканирование", en: "signature-based scanning"},
  {ru: "кремний", en: "silicon"},
  {ru: "одновременная многопоточность", en: "SMT / simultaneous multithreading"},
  {ru: "умные приборы / умная бытовая техника", en: "smart home appliances"},
  {ru: "программное обеспечение", en: "software"},
  {ru: "твердотельная технология", en: "solid state technology"},
  {ru: "исходный код", en: "source code"},
  {ru: "колонки (динамики)", en: "speakers"},
  {ru: "электронные таблицы", en: "spreadsheets"},
  {ru: "шпионские программы", en: "spyware"},
  {ru: "твердотельный накопитель", en: "SSD / solid state drive"},
  {ru: "протокол защищённых соединений", en: "SSL / secure sockets layer"},
  {ru: "топология звезда", en: "star topology"},
  {ru: "устройство хранения данных", en: "storage device"},
  {ru: "носитель информации", en: "storage medium"},
  {ru: "потоковое видео", en: "streaming video"},
  {ru: "абоненты", en: "subscribers"},
  {ru: "суперкомпьютер", en: "supercomputer"},
  {ru: "организующая программа", en: "supervisor program"},
  {ru: "переключатель / коммутатор", en: "switch"},
  {ru: "тактовый генератор", en: "system clock"},
  {ru: "системный блок", en: "system unit"},
  {ru: "планшет", en: "tablet"},
  {ru: "операционная система с режимом разделения времени", en: "timesharing operating systems"},
  {ru: "архивировать", en: "to archive"},
  {ru: "переходить по подозрительной ссылке", en: "to click a suspicious link"},
  {ru: "отказать в доступе", en: "to deny access"},
  {ru: "редактировать", en: "to edit"},
  {ru: "шифровать данные", en: "to encrypt data"},
  {ru: "стирать / удалять данные", en: "to erase / to delete / to remove"},
  {ru: "предотвратить несанкционированный доступ", en: "to prevent an unauthorized access"},
  {ru: "запустить заражённую программу", en: "to run an infected program"},
  {ru: "распространять вирусы", en: "to spread / to propagate viruses"},
  {ru: "обновлять антивирусное ПО", en: "to update antivirus software"},
  {ru: "сенсорный экран", en: "touch screen"},
  {ru: "сенсорная панель", en: "touchpad"},
  {ru: "дорожка (на диске)", en: "track"},
  {ru: "приёмопередатчик", en: "transceiver"},
  {ru: "скорость передачи данных", en: "transfer rate"},
  {ru: "запуск / активация вируса", en: "trigger"},
  {ru: "троянский конь", en: "trojan"},
  {ru: "витая пара", en: "twisted-pair cable"},
  {ru: "протокол пользовательских дейтаграмм", en: "UDP / user datagram protocol"},
  {ru: "неавторизованный / несанкционированный доступ", en: "unauthorized access"},
  {ru: "универсальный указатель ресурса", en: "URL / uniform resource locator"},
  {ru: "USB порт", en: "USB port / universal serial bus port"},
  {ru: "флеш-накопитель", en: "USB-flash drive / memory stick"},
  {ru: "электронные лампы", en: "vacuum tubes"},
  {ru: "виртуальная клавиатура", en: "virtual keyboard"},
  {ru: "коммутация виртуальных каналов", en: "virtual circuit switching"},
  {ru: "энергозависимый", en: "volatile"},
  {ru: "напряжение", en: "voltage"},
  {ru: "виртуальная реальность", en: "VR / virtual reality"},
  {ru: "конструктор веб-сайтов", en: "website builder"},
  {ru: "искажение информации на вебсайте", en: "website defacement"},
  {ru: "вес (в нейросети)", en: "weight"},
  {ru: "беспроводная локальная сеть", en: "WLAN / wireless local area network"},
  {ru: "текстовый редактор", en: "word processor"},
  {ru: "червь (вирус)", en: "worm"},
  {ru: "кэш с обратной записью / отложенной записью", en: "write-back cache"},
  {ru: "кэш со сквозной записью", en: "write-through cache"}
];

const ABBREVIATIONS = [
  {abbr: "2FA", full: "Two-Factor Authentication"},
  {abbr: "ADSL", full: "Asymmetric Digital Subscriber Line"},
  {abbr: "AI", full: "Artificial Intelligence"},
  {abbr: "ALU", full: "Arithmetic Logic Unit"},
  {abbr: "ANN", full: "Artificial Neural Network"},
  {abbr: "AR", full: "Augmented Reality"},
  {abbr: "ASCII", full: "American Standard Code for Information Interchange"},
  {abbr: "BASIC", full: "Beginner's All-purpose Symbolic Instruction Code"},
  {abbr: "BD", full: "Blu-ray Disc"},
  {abbr: "BIOS", full: "Basic Input/Output System"},
  {abbr: "CAPTCHA", full: "Completely Automated Public Turing test to tell Computers and Humans Apart"},
  {abbr: "CD-R", full: "Compact Disc Recordable"},
  {abbr: "CD-ROM", full: "Compact Disc Read-Only Memory"},
  {abbr: "CD-RW", full: "Compact Disc Rewritable"},
  {abbr: "CGI", full: "Computer-Generated Image"},
  {abbr: "CLI", full: "Command Line Interface"},
  {abbr: "CNN", full: "Convolutional Neural Network"},
  {abbr: "CPU", full: "Central Processing Unit"},
  {abbr: "CSS", full: "Cascading Style Sheets"},
  {abbr: "DDoS", full: "Distributed Denial of Service"},
  {abbr: "DDR4", full: "Double Data Rate 4"},
  {abbr: "DNS", full: "Domain Name System"},
  {abbr: "DoS", full: "Denial of Service"},
  {abbr: "DRAM", full: "Dynamic Random Access Memory"},
  {abbr: "DSL", full: "Digital Subscriber Line"},
  {abbr: "DVD", full: "Digital Versatile Disc"},
  {abbr: "EEPROM", full: "Electrically Erasable Programmable Read-Only Memory"},
  {abbr: "ENIAC", full: "Electronic Numerical Integrator and Computer"},
  {abbr: "EPROM", full: "Erasable Programmable Read-Only Memory"},
  {abbr: "FGT", full: "Floating Gate Transistors"},
  {abbr: "FORTRAN", full: "FORmula TRANslator"},
  {abbr: "FTP", full: "File Transfer Protocol"},
  {abbr: "GB", full: "Gigabyte"},
  {abbr: "GHz", full: "Gigahertz"},
  {abbr: "GSM", full: "Global System for Mobile Communications"},
  {abbr: "GUI", full: "Graphical User Interface"},
  {abbr: "HDD", full: "Hard Disk Drive"},
  {abbr: "HLAI", full: "Human-Like Artificial Intelligence / Human-Level Artificial Intelligence"},
  {abbr: "HTML", full: "Hyper Text Markup Language"},
  {abbr: "HTTP", full: "Hyper Text Transfer Protocol"},
  {abbr: "IBM", full: "International Business Machines"},
  {abbr: "ICANN", full: "Internet Corporation for Assigned Names and Numbers"},
  {abbr: "IoT", full: "Internet of Things"},
  {abbr: "IR", full: "Instruction Register"},
  {abbr: "ISDN", full: "Integrated Services Digital Network"},
  {abbr: "ISP", full: "Internet Service Provider"},
  {abbr: "JS", full: "JavaScript"},
  {abbr: "JVM", full: "Java Virtual Machine"},
  {abbr: "KB", full: "Kilobyte"},
  {abbr: "LAN", full: "Local Area Network"},
  {abbr: "LCD", full: "Liquid Crystal Display"},
  {abbr: "MAC address", full: "Media Access Control address"},
  {abbr: "MAN", full: "Metropolitan Area Network"},
  {abbr: "MFA", full: "Multi-Factor Authentication"},
  {abbr: "ML", full: "Machine Learning"},
  {abbr: "MROM", full: "Masked Read-Only Memory"},
  {abbr: "MS Word", full: "Microsoft Word"},
  {abbr: "MS-DOS", full: "Microsoft Disk Operating System"},
  {abbr: "NAND Flash", full: "Not AND Flash"},
  {abbr: "NN", full: "Neural Networks"},
  {abbr: "NOR Flash", full: "Not OR Flash"},
  {abbr: "OOP", full: "Object-Oriented Programming"},
  {abbr: "OS", full: "Operating System"},
  {abbr: "OSI", full: "Open System Interconnection"},
  {abbr: "PAN", full: "Personal Area Network"},
  {abbr: "PC (computer)", full: "Personal Computer"},
  {abbr: "PC (register)", full: "Program Counter"},
  {abbr: "PHP", full: "Hypertext Preprocessor"},
  {abbr: "PROM", full: "Programmable Read-Only Memory"},
  {abbr: "RAM", full: "Random Access Memory"},
  {abbr: "RNN", full: "Recurrent Neural Network"},
  {abbr: "ROM", full: "Read-Only Memory"},
  {abbr: "SDRAM", full: "Synchronous Dynamic Random Access Memory"},
  {abbr: "SDSL", full: "Symmetric Digital Subscriber Line"},
  {abbr: "SEO", full: "Search Engine Optimization"},
  {abbr: "SMT", full: "Simultaneous Multi-threading Technology"},
  {abbr: "SMTP", full: "Simple Mail Transfer Protocol"},
  {abbr: "SQL", full: "Structured Query Language"},
  {abbr: "SRAM", full: "Static Random Access Memory"},
  {abbr: "SSD", full: "Solid State Drive"},
  {abbr: "SSL", full: "Secure Sockets Layer"},
  {abbr: "TB", full: "Terabyte / TByte"},
  {abbr: "TCP/IP", full: "Transmission Control Protocol / Internet Protocol"},
  {abbr: "UDP", full: "User Datagram Protocol"},
  {abbr: "UIDs", full: "Unique Identifiers"},
  {abbr: "UNIVAC I", full: "Universal Automatic Computer"},
  {abbr: "URL", full: "Uniform Resource Locator"},
  {abbr: "USB", full: "Universal Serial Bus"},
  {abbr: "VDSL", full: "Very High Bit Rate DSL"},
  {abbr: "VR", full: "Virtual Reality"},
  {abbr: "WAF", full: "Web Application Protection Firewall"},
  {abbr: "WAN", full: "Wide Area Network"},
  {abbr: "Wi-Fi", full: "Wireless Fidelity"},
  {abbr: "WiMAX", full: "Worldwide Interoperability for Microwave Access"},
  {abbr: "WIMP", full: "Windows Icons Menus Pointer"},
  {abbr: "WLAN", full: "Wireless Local Area Network"},
  {abbr: "WWW", full: "World Wide Web"},
  {abbr: "WYSIWYG", full: "What You See Is What You Get"},
  {abbr: "Yandex", full: "Yet Another iNDEXer"}
];

const DEFINITIONS = [
  {term: "Abacus", def: "an ancient counting tool invented in China around 1300 BC used to perform basic arithmetical operations such as addition, subtraction, multiplication, and division"},
  {term: "Analytical Engine", def: "a mechanical computer designed in the 1830s by Charles Babbage, considered the first machine resembling modern computers because it contained an ALU, control unit, memory, and input/output system"},
  {term: "Arithmetic Logic Unit (ALU)", def: "a fundamental component of a computer's processor responsible for performing mathematical calculations and logical operations"},
  {term: "Integrated Circuit (IC)", def: "a miniature electronic circuit consisting of various interconnected components fabricated onto a single semiconductor substance; also called microchip"},
  {term: "Moore's Law", def: "a theory based on a prediction made by Gordon Moore in 1965 stating that computer processing power doubles approximately every two years as more transistors are placed on a circuit"},
  {term: "Pascaline", def: "the first mechanical adding machine, built by Blaise Pascal between 1642 and 1644, capable of performing addition and subtraction"},
  {term: "Parallel processing", def: "a computing method where multiple processors or cores perform several calculations or execute processes simultaneously"},
  {term: "Semiconductor", def: "a material, such as silicon, whose ability to conduct electricity increases as its temperature rises"},
  {term: "Transistor", def: "a semiconductor that controls voltage or current flow in electronic signals acting as a switch; replaced vacuum tubes in second-generation computers"},
  {term: "Vacuum tube", def: "an electronic device that regulates electron movement in a vacuum; an early component used in first-generation computers (1940s) to control the flow of electricity"},
  {term: "First-generation computers", def: "electronic digital computers (1940s) characterized by the use of vacuum tubes, enormous physical size, high electricity consumption, and the ability to solve only one problem at a time"},
  {term: "Second-generation computers", def: "computers (late 1950s–early 1960s) which utilized transistors instead of vacuum tubes; ten times faster, smaller in size, and required less maintenance"},
  {term: "Third-generation computers", def: "computers (1965–1972) built with integrated circuits, enabling speeds of a million calculations per second and significantly lower production and maintenance costs"},
  {term: "Fourth-generation computers", def: "computers (mid-1970s–present) based on thousands of circuits placed on a single microprocessor chip, supporting GUIs and network connectivity"},
  {term: "Fifth-generation computers", def: "modern computers based on parallel processing and Artificial Intelligence, designed to simulate human reasoning and respond to natural language input"},
  {term: "Desktop PC", def: "a personal computer designed for use in a single, stationary location, typically consisting of a system unit, monitor, keyboard, and mouse"},
  {term: "Laptop", def: "a portable, lightweight computer with a hinged design, featuring a flat LCD screen, a built-in keyboard with a touchpad, and a battery for mobile use"},
  {term: "Mainframe", def: "a large, powerful computer capable of supporting multiple users and thousands of simultaneous queries; often used for large-scale data processing in banks and big corporations"},
  {term: "Netbook", def: "a mobile computer that is typically smaller than a laptop, popular for basic web browsing and often having fewer functions than a full-sized laptop"},
  {term: "Server", def: "a central computer connected to a network of client workstations, designed to store data and provide services with higher processing power and memory than a standard workstation"},
  {term: "Supercomputer", def: "the fastest type of computer, containing tens of thousands of processors for simultaneous execution of data-intensive tasks such as weather forecasting and aerodynamics"},
  {term: "Tablet PC", def: "a highly portable mobile device with a touch screen interface, typically lacking a physical keyboard and using a mobile operating system"},
  {term: "Touchpad", def: "a sensitive pad built into a laptop keyboard that allows the user to move the pointer on the screen by touch, serving as a replacement for a mouse"},
  {term: "BIOS", def: "a ROM chip on the motherboard containing firmware used to perform hardware initialization during the booting process"},
  {term: "Bus", def: "an electrical channel that carries signals and allows devices inside the computer to communicate with each other"},
  {term: "Central Processing Unit (CPU)", def: "the 'brain' of the computer, built into a single chip (microprocessor), responsible for executing program instructions and coordinating all other units"},
  {term: "Clock speed", def: "the measurement of how many cycles a CPU executes per second, typically measured in gigahertz (GHz)"},
  {term: "Control Unit", def: "the component of the CPU that interprets instructions from the user's program and directs the rest of the hardware to execute them"},
  {term: "Expansion slot", def: "a socket on the motherboard that allows users to install expansion cards to add features like sound or network capabilities"},
  {term: "Hardware", def: "any physical, electronic, or mechanical part of a computer system that can be seen or touched"},
  {term: "Input device", def: "a hardware unit that enables the user to enter data into the computer's memory, such as a keyboard, mouse, or scanner"},
  {term: "Motherboard", def: "the main circuit board of a computer that holds the CPU, memory chips, expansion slots, and controllers for peripherals"},
  {term: "Mouse", def: "a small input device used to specify the position of the cursor or to make choices from menus"},
  {term: "Output device", def: "any peripheral that allows the user to extract or view the finished results from the system, such as a monitor or printer"},
  {term: "Peripherals", def: "physical units attached to the computer, including input, output, and storage devices"},
  {term: "Program counter (PC)", def: "a CPU register that keeps track of the next instruction to be performed"},
  {term: "Instruction register (IR)", def: "a CPU register that holds the instruction that is being executed now"},
  {term: "RAM", def: "volatile main memory used to temporarily store data and instructions while they are being processed by the CPU; its contents are lost when power is turned off"},
  {term: "Registers", def: "high-speed memory units within the CPU used to store and control data immediately needed for instruction execution"},
  {term: "ROM", def: "non-volatile memory containing permanent instructions and routines for basic CPU operations, such as the BIOS"},
  {term: "Scanner", def: "an input device that converts images, printed text or handwriting into a digital image"},
  {term: "Speaker", def: "a device that provides sound output"},
  {term: "Storage device", def: "a peripheral device used for permanent or long-term storage of data and programs, such as hard drives or flash drives"},
  {term: "SMT (Simultaneous Multi-Threading)", def: "a technology that allows two threads to run on a single core, which enables more effective use of CPU resources and improves overall performance"},
  {term: "Cache hit", def: "a situation when the processor finds data in the cache area"},
  {term: "Cache memory", def: "a type of very fast volatile memory that holds a small amount of recently accessed data and acts as a buffer between the main memory and the processor"},
  {term: "Cache miss", def: "a situation when the processor does not find data in the cache area and reads it in the slower RAM"},
  {term: "Primary memory", def: "an internal storage device, such as cache or RAM, which can be directly accessed by the CPU with minimum or no delay"},
  {term: "Write-back cache", def: "a method changing data in the cache area first, while RAM is updated later"},
  {term: "Write-through cache", def: "a method of refreshing data in the cache and main memory simultaneously"},
  {term: "Access time", def: "the amount of time it takes for a storage device to search and locate the data you plan to open, copy, move"},
  {term: "Capacity", def: "the maximum amount of data a storage device can contain"},
  {term: "CD-R", def: "a type of CD which is released blank and can be recorded on once only"},
  {term: "CD-ROM", def: "a type of CD which comes pre-recorded and doesn't allow to change data stored on it"},
  {term: "CD-RW", def: "a type of CD whose data can be written, read, erased, and rewritten"},
  {term: "Flash memory", def: "a type of non-volatile memory which works by using electronic circuits to store and retrieve data"},
  {term: "Floppy disk", def: "an outdated storage device of low capacity made of flexible plastic material upon which data is stored on magnetic tracks"},
  {term: "Magnetic storage", def: "a type of storage in which data is written by magnetizing particles on a disk or tape"},
  {term: "NOR flash", def: "a type of flash memory that provides fast access to small amounts of data used in bootloaders and firmware"},
  {term: "NAND flash", def: "a type of flash memory that provides slow access to large amounts of data used in SSDs and USB flash drives"},
  {term: "Optical storage", def: "a type of storage in which data is written as a series of reflective marks and read with a laser"},
  {term: "Read/write head", def: "a part of an HDD which reads and writes data by magnetizing and demagnetizing fields on spinning platters"},
  {term: "Transfer rate", def: "the average speed at which data can be transmitted from one device to another, often measured in megabytes per second"},
  {term: "CLI", def: "the way to interact with a computer system through typing various commands in the form of lines of text"},
  {term: "Compatible", def: "being able to work with another device or program"},
  {term: "Device driver", def: "a type of software that controls specific hardware of the computer system"},
  {term: "Firmware", def: "permanent software or set of instructions stored in ROM of the computer system"},
  {term: "GUI", def: "a user-friendly interface based on graphics; it uses a WIMP environment"},
  {term: "Operating system", def: "a set of programs that manage the computer's hardware resources, establish a user interface, and provide the environment for application programs to run"},
  {term: "Open-source software", def: "a type of computer software whose copyright holder grants users the rights to use, study, change, and distribute the software to anyone and for any purpose"},
  {term: "Proprietary software", def: "non-free software whose users are not allowed to share, modify it, and distribute the modifications"},
  {term: "Spreadsheet", def: "a computer application for organization, analysis and storage of data in a tabular form"},
  {term: "Word processor", def: "a computer application used to compose and edit texts"},
  {term: "Preemptive multitasking", def: "a type of multitasking where the operating system can initiate a context switch to satisfy the scheduling policy's priority, thus preempting the active task"},
  {term: "Cooperative multitasking", def: "a computer multitasking technique in which the operating system never initiates a context switch from a running process to another process"},
  {term: "Topology", def: "the configuration of the elements (nodes) of a network"},
  {term: "Local area network (LAN)", def: "a collection of devices connected together in one physical location, such as a building, office, or home"},
  {term: "Metropolitan Area Network (MAN)", def: "a high-speed network that interconnects multiple LANs within a specific geographic area, such as a city, large campus, or municipality"},
  {term: "Wide Area Network (WAN)", def: "a type of computer network that connects computers and other devices over a large geographical area (a country or a continent)"},
  {term: "Network hub", def: "a node that broadcasts data to every computer or Ethernet-based device connected to it without restriction"},
  {term: "Network switch", def: "identical to a network hub, but unlike a hub, it forwards data to the specific device only based on its MAC address"},
  {term: "Bus topology", def: "a network setup where all nodes (computers, servers, printers) connect directly to a single, central cable, known as the backbone or bus"},
  {term: "Peer-to-peer network", def: "a network architecture in which all the computers have the same capabilities, i.e. share files and peripherals, without requiring a separate server computer"},
  {term: "Client-server network", def: "a computing model in which multiple clients connect to a central server to access resources, such as files, applications, and data"},
  {term: "Ring topology", def: "a LAN topology, in which all devices are interconnected in a continuous loop"},
  {term: "Tree topology", def: "a type of network setup that combines elements from both star and bus topologies to create a hierarchical structure"},
  {term: "Mesh topology", def: "a network configuration where every device is interconnected with every other device, providing multiple routes for data to travel"},
  {term: "Hybrid topology", def: "a network structure that combines two or more different types of topologies into a single system"},
  {term: "Star topology", def: "a LAN topology, in which all data flows through a central hub, a common connection point for the devices on the network"},
  {term: "Ad hoc topology", def: "a wireless peer-to-peer network that does not rely on the existing infrastructure"},
  {term: "Bridge", def: "a hardware component connecting networks that use the same protocol"},
  {term: "Router", def: "a networking device that can send data packets from one network to another"},
  {term: "Gateway", def: "a device or software used to enable communication between two networks that may be using different protocols"},
  {term: "Computer network", def: "a group of computers that use a set of common communication protocols over digital interconnections for the purpose of sharing resources located on or provided by the network nodes"},
  {term: "Latency", def: "the time delay between a user's action (request) and the system's response, typically measured in milliseconds (ms)"},
  {term: "Modem", def: "a computer hardware device that converts data from a digital format into a format suitable for an analog transmission medium such as telephone or radio"},
  {term: "Wired networks", def: "communication systems that connect devices using physical cables, such as Ethernet (twisted pair), fiber optics, or coaxial cables, to a central router or switch"},
  {term: "Wireless network", def: "a computer network that uses wireless data connections between network nodes"},
  {term: "Wireless LAN (WLAN)", def: "a wireless computer network that forms a local area network by linking devices over Wi-Fi radio signals"},
  {term: "Backbone network", def: "a high-capacity communications network that serves as the principal data path interconnecting multiple subnetworks"},
  {term: "OSI model", def: "a set of rules that explains how different computer systems communicate over a network"},
  {term: "Application layer", def: "the layer that serves as the interface between the end-user applications and the underlying network services"},
  {term: "Presentation layer", def: "the layer that acts as a translator and negotiator, ensuring that data from the application layer can be understood by the receiving system"},
  {term: "Session layer", def: "the layer that manages the establishment, maintenance, and termination of connections (sessions) between applications on different devices"},
  {term: "Transport layer", def: "the layer that ensures reliable, ordered, and error-checked delivery of data between applications on different network hosts"},
  {term: "Network layer", def: "the layer that handles routing, forwarding, and logical addressing (IP addresses) to send data packets between different networks or devices"},
  {term: "Data link layer", def: "the OSI model layer responsible for node-to-node data transfer on a local network segment, ensuring reliable, error-free transmission between directly connected devices"},
  {term: "Physical layer", def: "the lowest layer of the OSI model, responsible for transmitting raw bits of data from one node to the other over physical cable or wireless connection"},
  {term: "MAC address", def: "a 12-digit hexadecimal number that uniquely identifies every device connected to a network"},
  {term: "IP address", def: "the unique identifying number assigned to every device connected to the internet"},
  {term: "Bluetooth", def: "a wireless technology that allows mobile devices and other peripheral devices to communicate over short distances"},
  {term: "Coaxial cable", def: "a type of cable that consists of four main components: inner conductor, insulation, metal shield, and jacket"},
  {term: "Virtual circuit switching", def: "an approach in which a path is built between the source and the destination points through which all packets are routed"},
  {term: "Datagram switching", def: "a packet switching method that treats each packet as a separate entity; each packet is routed via the network on its own through different paths, then reassembled at the destination"},
  {term: "Digital Subscriber Line", def: "a broadband communication technology designed for use on telephone lines; allows a single phone connection to be used for both Internet service and voice calls at the same time"},
  {term: "Fiber-optic technology", def: "the fastest wired way to access the Internet, transmitting information as pulses of light through strands of fiber made of glass or plastic over long distances"},
  {term: "Bandwidth", def: "the measure of how much information can pass through a data connection in a given amount of time, measured in bits per second"},
  {term: "Cellular network", def: "a radio-based communication network distributed over land areas called cells, each served by a fixed-location transceiver known as a cell tower"},
  {term: "Dial-up connection", def: "the least expensive but also the slowest way to access the Internet, which uses a standard phone line and analog modem"},
  {term: "TCP/IP stack", def: "a four-layer protocol model used on the Internet to govern how data is transmitted between computers; named after the two main protocols TCP and IP"},
  {term: "World Wide Web (WWW)", def: "an information system accessible through the Internet where documents and other web resources are identified by a Uniform Resource Locator (URL)"},
  {term: "Ranking", def: "the process of ordering the search results from most relevant to least relevant"},
  {term: "Web crawler", def: "a special program also known as a spider that regularly browses the web to discover new content by following hyperlinks and storing copies of pages in a search engine's index"},
  {term: "Human-powered directories", def: "systems that depend on human editors for their listings; a directory gets its information from submissions or from editors who write descriptions for reviewed sites"},
  {term: "Meta-search engine", def: "a type of search engine which does not have a database of indexed pages of its own; instead, it sends users' queries to several other search engines and compiles top results"},
  {term: "Search bar", def: "a field on the screen that allows users to enter keywords or phrases to find specific content"},
  {term: "Web browser", def: "software that serves as a gateway to the World Wide Web; identifies individual URLs and displays the corresponding page on the user's device"},
  {term: "Search engine", def: "a software system that scans, indexes, and retrieves web content to help users find information online"},
  {term: "Hyperlink", def: "a highlighted word or image in a hypertext document that takes a user to another location when he/she clicks on it"},
  {term: "Backend development", def: "a field of web development that is associated with the part of the site connected to the server"},
  {term: "Frontend development", def: "a field of web development that focuses on the visible part of the site"},
  {term: "HTML", def: "a code used to describe the structure of information on a webpage telling the web browser how to display its content"},
  {term: "JavaScript", def: "a programming language used by web developers to create dynamically updating content, use animations, pop-up menus, clickable buttons, etc."},
  {term: "CSS", def: "a mechanism for adding style (e.g. fonts, colors, spacing) to web documents"},
  {term: "SEO", def: "a set of improvements that increases visibility of a site and helps it rank higher on the results page"},
  {term: "Website builder", def: "a platform that can be used to create a website without having to code"},
  {term: "Assembly language", def: "a low-level programming language that uses symbolic instructions rather than raw binary coding to communicate directly with a computer's hardware"},
  {term: "Object-oriented programming (OOP)", def: "a programming paradigm that relies on the concept of classes and objects; objects are software entities that encapsulate data and functions"},
  {term: "Compiler", def: "a special program that converts a source program (written in a high-level language) into object code in one go"},
  {term: "Interpreter", def: "a special program that translates the source code line by line, as the program is running"},
  {term: "Inheritance", def: "the ability of one class to use properties and behavior of another class"},
  {term: "Polymorphism", def: "a programming language's ability to process objects differently depending on their data type or class"},
  {term: "Encapsulation", def: "a fundamental concept that combines data (attributes) and methods (functions) into a single unit"},
  {term: "Source code", def: "a set of instructions typically written in a high-level programming language that defines how a program or application should function"},
  {term: "Machine code", def: "a code made of just two numbers (0 and 1)"},
  {term: "Debugging", def: "the technique of detecting and correcting errors which may occur in programs"},
  {term: "Spyware", def: "malicious software designed to enter a computer device, gather data about a person or organization and forward it to a third party without a user's consent"},
  {term: "Adware", def: "a form of financially supported malware that usually presents itself as unwanted commercials"},
  {term: "Keylogger", def: "a type of spyware used to monitor and record each keystroke on a specific keyboard; most often used for stealing passwords"},
  {term: "Worm", def: "a standalone malicious computer program that replicates itself to infect other computers; able to spread across the network directly without attaching itself to a host file"},
  {term: "Hijacking", def: "a type of cybercrime which involves redirecting anyone trying to visit a certain site elsewhere"},
  {term: "DDoS attack", def: "an attack where hackers overload networks and servers with traffic so that computer systems are unable to keep up with legitimate needs"},
  {term: "Trojan", def: "a type of malware that misleads users of its true intent by pretending to be a useful program"},
  {term: "Phishing", def: "a type of cybercrime where the attacker sends a fake message designed to trick a person into revealing sensitive information"},
  {term: "Ransomware", def: "a type of malware that threatens to publish the victim's data, encrypts the victim's data or blocks access to the device unless a payment is made"},
  {term: "Miner", def: "a virus which uses your computer power to earn cryptocurrency for others"},
  {term: "Piracy", def: "unauthorized copying of a program for sale or distributing to other users"},
  {term: "Backdoor", def: "a technique that involves leaving, within a completed program, an illicit program that allows unauthorized and unknown entry"},
  {term: "Defacement", def: "a cybercrime which involves changing the information shown on another person's website"},
  {term: "Salami shaving", def: "a computer crime in which a program is altered so that it transfers a small amount of money from a large number of accounts to make a large profit"},
  {term: "Misdirection routine", def: "the component that allows a virus to hide itself"},
  {term: "Trigger", def: "the component of a virus that activates payload"},
  {term: "Payload", def: "the component of a virus that does the damage to the computer system"},
  {term: "Reproduction routine", def: "the component that allows the virus to self-replicate and infect other programs"},
  {term: "Firewall", def: "a combination of software and hardware used to protect private networks by filtering incoming data traffic"},
  {term: "Signature", def: "a distinguishing feature that every computer virus contains"},
  {term: "Heuristic scanning", def: "a type of malware detection technique which allows identifying potentially malicious software without having an exact match in signature database"},
  {term: "Cybersecurity", def: "the practice employed to protect and secure computers, servers, networks, mobile devices, electronic systems, and data from being attacked"},
  {term: "Multi-factor authentication (MFA)", def: "a user verification technology that requires more than one type of user validation"},
  {term: "Encryption", def: "a way of encoding data so that only authorized parties can understand the information"},
  {term: "Brute force", def: "a cybersecurity threat where a hacker attempts to access a system by systematically testing different passwords"},
  {term: "Password", def: "secret data, typically a string of characters, usually used to confirm a user's identity"},
  {term: "Cryptanalysis", def: "a method of spotting a weakness in the cipher aiming to decrypt encoded data"},
  {term: "Secure Sockets Layer (SSL)", def: "an Internet security protocol that encrypts data to ensure secure communication between devices over a network"},
  {term: "Web application firewall (WAF)", def: "helps protect web applications by filtering and monitoring HTTP traffic between a web application and the Internet"},
  {term: "Ciphertext", def: "encrypted text transformed from plaintext using an encryption algorithm"},
  {term: "Cryptography", def: "the process of hiding or coding information so that only the person a message was intended for can read it"},
  {term: "Cryptographic key", def: "a randomized string of bits used to encrypt and/or decrypt data"},
  {term: "Symmetric encryption", def: "the process of using a single key to both encrypt and decrypt data"},
  {term: "Asymmetric encryption", def: "a security method that uses a mathematically linked pair of keys—a public key for encryption and a private key for decryption—to protect data; also called public-key cryptography"},
  {term: "Antivirus software", def: "designed to detect, present and take action to disarm or remove malicious software from your computer such as viruses, worms and Trojan horses"},
  {term: "Packet filtering firewall", def: "a network security device that filters incoming and outgoing network packets based on a predefined set of rules"},
  {term: "Backup program", def: "a program that stores a copy of data on a storage device to keep it safe"},
  {term: "Incremental backup", def: "a backup type that only copies data that has been changed or created since the previous full, differential or incremental backup"},
  {term: "Differential backup", def: "a data protection method that copies all files changed since the last full backup"},
  {term: "Artificial Intelligence (AI)", def: "a technology that simulates human intelligence in computer systems; enables a computer or a robot controlled by a computer to do tasks that are usually done by humans"},
  {term: "Internet of Things (IoT)", def: "a system of interrelated computing devices, mechanical, and digital machines provided with the ability to share data in order to automate processes"},
  {term: "Virtual Reality (VR)", def: "a computer-generated space in which the user interacts with artificial objects through 3-D computer simulation"},
  {term: "Neural Networks (NN)", def: "computing systems with interconnected nodes that resemble neurons in the human brain; using algorithms, they can recognize hidden patterns and correlations in raw data"},
  {term: "Augmented Reality (AR)", def: "an enhanced version of the real physical world, which integrates digital information with the existing environment in real time"},
  {term: "Backpropagation", def: "an algorithm that is designed to test for errors working back from output nodes to input nodes"},
  {term: "Unique Identifier (UID)", def: "a numeric or alphanumeric string assigned to a specific entity—such as a user, device, file, or database record—to distinguish it from others within a system"},
  {term: "Machine Learning (ML)", def: "a subset of AI that enables software to learn from data, identifying patterns to make predictions or decisions without being explicitly programmed"},
  {term: "Artificial neurons", def: "units arranged in a series of layers, each of which connects to the layers on either side"},
  {term: "Input units", def: "the layers of artificial neurons designed to receive various forms of information from the outside world that the network will attempt to learn about, recognize, or process"},
  {term: "Output units", def: "the layers of artificial neurons designed to signal how the network responds to the information it has learned"},
  {term: "Hidden units", def: "the layers of artificial neurons between the input and output layers that process information and form the core computational engine of a neural network"},
  {term: "Weight", def: "a numerical value representing the strength of the connection between two units in a neural network; a positive value indicates excitation and a negative value indicates inhibition"},
  {term: "Human-level artificial intelligence (HLAI)", def: "a term used to describe artificial intelligence systems that have human-like abilities in terms of reasoning, learning, perception, and problem solving"},
  {term: "Turing Test", def: "a test of whether a computer can show intelligent behavior like that of a human, done by seeing if a tester can tell whether the answers come from the computer or from a person"}
];

window.DATA = { translations: TRANSLATIONS, abbreviations: ABBREVIATIONS, definitions: DEFINITIONS };
